server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: el Debbo
  data:
    mongodb:
      database: items-service-db
      uri: mongodb+srv://khalil:NIhnpSnrYbFHhHJ8@booksapi.3jfawpd.mongodb.net
  session:
    mongodb:
      collection-name: sessions
  devtools:
    restart:
      enabled: true
